// Generated from engine/crates/api by `cargo test -p dramatis`. Do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Which form the app is in and whether the corpus loaded. */
	appStatus: () => typedError<AppStatus, ApiError>(__TAURI_INVOKE("app_status")),
	/**  The corpus's runtime phrasing. */
	wording: () => typedError<Wording, ApiError>(__TAURI_INVOKE("wording")),
	/**
	 *  The user opened the app or came back from idle. Returns the waiting panel at once
	 *  (no model call). What the engine then says arrives as `MessageAdded` (streamed
	 *  through `MessageDelta` first) in the host's channel: on the very first open with a
	 *  chat endpoint that is the host's introduction, shown with the [`coldstart`] card;
	 *  afterwards at most one line about a non-empty digest. Then at most one person's
	 *  opening, in their own channel. Nothing is said while quota is quiet or exhausted.
	 * 
	 *  [`coldstart`]: Api::coldstart
	 */
	presence: () => typedError<Digest, ApiError>(__TAURI_INVOKE("presence")),
	/**
	 *  The first-open recommendation card: people picked when the corpus was built,
	 *  each with a reason from their material. Everyone on it is still frozen.
	 */
	coldstart: () => typedError<Candidate[], ApiError>(__TAURI_INVOKE("coldstart")),
	/**  The in-world date and the local time, for the header. */
	clock: () => typedError<Clock, ApiError>(__TAURI_INVOKE("clock")),
	/**  The waiting panel. Pure data. */
	digest: () => typedError<Digest, ApiError>(__TAURI_INVOKE("digest")),
	roster: () => typedError<Roster, ApiError>(__TAURI_INVOKE("roster")),
	personPage: (person: PersonId) => typedError<PersonPage, ApiError>(__TAURI_INVOKE("person_page", { person })),
	/**  People who know about a topic, each with a reason. Disabled people never appear. */
	findPeople: (topic: string) => typedError<Candidate[], ApiError>(__TAURI_INVOKE("find_people", { topic })),
	setMode: (target: Target, mode: Mode) => typedError<null, ApiError>(__TAURI_INVOKE("set_mode", { target, mode })),
	channels: () => typedError<ChannelSummary[], ApiError>(__TAURI_INVOKE("channels")),
	/**  Newest last; `before` pages backwards. */
	history: (channel: ChannelId, before: string | null, limit: number) => typedError<Message[], ApiError>(__TAURI_INVOKE("history", { channel, before, limit })),
	/**  The direct channel with a person, created on first use. */
	openDirect: (person: PersonId) => typedError<ChannelId, ApiError>(__TAURI_INVOKE("open_direct", { person })),
	/**  The host's channel. */
	hostChannel: () => typedError<ChannelId, ApiError>(__TAURI_INVOKE("host_channel")),
	/**  Append a user turn. The reply streams back as events. */
	sendMessage: (channel: ChannelId, text: string, image: {
	/**  `image/png`, `image/jpeg`, ... */
	mime: string,
	data_base64: string,
} | null) => typedError<MessageId, ApiError>(__TAURI_INVOKE("send_message", { channel, text, image })),
	/**  Pass a quoted excerpt to someone else; their answer lands in their direct channel. */
	relay: (excerpt: string, from: MessageId, to: PersonId) => typedError<ChannelId, ApiError>(__TAURI_INVOKE("relay", { excerpt, from, to })),
	/**  Everything before this message has been seen. */
	markRead: (channel: ChannelId, upTo: MessageId) => typedError<null, ApiError>(__TAURI_INVOKE("mark_read", { channel, upTo })),
	createGroup: (members: PersonId[], topic: string | null) => typedError<ChannelId, ApiError>(__TAURI_INVOKE("create_group", { members, topic })),
	deleteGroup: (channel: ChannelId) => typedError<null, ApiError>(__TAURI_INVOKE("delete_group", { channel })),
	/**
	 *  Ask a person to look into a question. `turns` absent: the tier's default.
	 *  `parent`: file it under a pinned question.
	 */
	ask: (person: PersonId, question: string, turns: number | null, parent: string | null) => typedError<TaskId, ApiError>(__TAURI_INVOKE("ask", { person, question, turns, parent })),
	tasks: () => typedError<TaskSummary[], ApiError>(__TAURI_INVOKE("tasks")),
	caseFile: (task: TaskId) => typedError<CaseFile, ApiError>(__TAURI_INVOKE("case_file", { task })),
	/**  Pin a question nobody is on yet. */
	openCase: (question: string) => typedError<TaskId, ApiError>(__TAURI_INVOKE("open_case", { question })),
	pinTask: (task: TaskId) => typedError<null, ApiError>(__TAURI_INVOKE("pin_task", { task })),
	unpinTask: (task: TaskId) => typedError<null, ApiError>(__TAURI_INVOKE("unpin_task", { task })),
	/**  Write or replace the conclusion; replacing retracts the old one. */
	writeConclusion: (task: TaskId, text: string) => typedError<FactId, ApiError>(__TAURI_INVOKE("write_conclusion", { task, text })),
	facts: (filter: FactFilter) => typedError<FactList, ApiError>(__TAURI_INVOKE("facts", { filter })),
	/**  Retract and write anew; returns the new fact. */
	editFact: (fact: FactId, text: string) => typedError<FactId, ApiError>(__TAURI_INVOKE("edit_fact", { fact, text })),
	deleteFact: (fact: FactId) => typedError<null, ApiError>(__TAURI_INVOKE("delete_fact", { fact })),
	restoreFact: (fact: FactId) => typedError<null, ApiError>(__TAURI_INVOKE("restore_fact", { fact })),
	/**  Library-mode search: the whole corpus, no memories. */
	searchCorpus: (query: string, persons: PersonId[]) => typedError<SearchResults, ApiError>(__TAURI_INVOKE("search_corpus", { query, persons })),
	resolveCitation: (citation: Citation) => typedError<CitationView, ApiError>(__TAURI_INVOKE("resolve_citation", { citation })),
	avatar: (person: PersonId) => typedError<{
	path: string,
} | null, ApiError>(__TAURI_INVOKE("avatar", { person })),
	/**  Synthesize (or reuse the cached audio for) one message's speech. */
	ttsPlay: (message: MessageId) => typedError<MediaFile, ApiError>(__TAURI_INVOKE("tts_play", { message })),
	ttsVoices: () => typedError<string[], ApiError>(__TAURI_INVOKE("tts_voices")),
	setVoice: (person: PersonId, voice: string | null) => typedError<null, ApiError>(__TAURI_INVOKE("set_voice", { person, voice })),
	quota: () => typedError<QuotaStatus, ApiError>(__TAURI_INVOKE("quota")),
	setTier: (tier: Tier) => typedError<null, ApiError>(__TAURI_INVOKE("set_tier", { tier })),
	settings: () => typedError<Settings, ApiError>(__TAURI_INVOKE("settings")),
	updateSettings: (settings: Settings) => typedError<null, ApiError>(__TAURI_INVOKE("update_settings", { settings })),
	endpoints: () => typedError<EndpointsView, ApiError>(__TAURI_INVOKE("endpoints")),
	addProfile: (profile: Profile) => typedError<null, ApiError>(__TAURI_INVOKE("add_profile", { profile })),
	/**  Replace the profile called `name` (which may rename it). */
	updateProfile: (name: string, profile: Profile) => typedError<null, ApiError>(__TAURI_INVOKE("update_profile", { name, profile })),
	removeProfile: (name: string) => typedError<null, ApiError>(__TAURI_INVOKE("remove_profile", { name })),
	/**  `GET {base_url}/models`. An endpoint failure carries the endpoint's own text. */
	fetchModels: (profile: string) => typedError<string[], ApiError>(__TAURI_INVOKE("fetch_models", { profile })),
	/**  Store the key in the keychain. It is never returned by any command. */
	setKey: (profile: string, key: string) => typedError<null, ApiError>(__TAURI_INVOKE("set_key", { profile, key })),
	/**  `None` switches the role off (only meaningful for read-aloud). */
	setRole: (kind: RoleKind, role: {
	profile: string,
	model: string,
	/**
	 *  Passed as the endpoint's reasoning parameter; one value per session, never per call.
	 *  Absent: send none and let the endpoint default.
	 */
	reasoning?: string | null,
} | null) => typedError<null, ApiError>(__TAURI_INVOKE("set_role", { kind, role })),
};

/** Events */
export const events = {
	messageAdded: makeEvent<MessageAdded>("message-added"),
	messageDelta: makeEvent<MessageDelta>("message-delta"),
	modeChanged: makeEvent<ModeChanged>("mode-changed"),
	notification: makeEvent<Notification>("notification"),
	quotaChanged: makeEvent<QuotaChanged>("quota-changed"),
	rosterChanged: makeEvent<RosterChanged>("roster-changed"),
	toolCalled: makeEvent<ToolCalled>("tool-called"),
	worldChanged: makeEvent<WorldChanged>("world-changed"),
};

/* Types */
export type About = { kind: "task"; id: TaskId } | { kind: "fact"; id: FactId } | { kind: "person"; id: PersonId } | { kind: "user" } | { kind: "citation"; citation: Citation };

/**  Something a person did that the user has not seen, or that is due. */
export type Activity = { kind: "messaged"; at: Timestamp } | { kind: "replied"; task: TaskId; question: string; at: Timestamp } | { kind: "commitment_due"; fact: FactId; text: string; due: Timestamp } | { kind: "came_by"; at: Timestamp } | { kind: "birthday" };

/**
 *  Every command's error. A code the UI maps to an i18n key, never a sentence; `detail`
 *  carries only text that did not originate here (an endpoint's own error body, an OS
 *  error), shown verbatim.
 */
export type ApiError = { code: "not_implemented" } | { code: "not_found" } | 
/**  The request itself is malformed (empty text, unknown key, out-of-range value). */
{ code: "invalid"; field: string } | 
/**  The target is disabled and so does not exist for this purpose. */
{ code: "disabled"; person: PersonId } | 
/**  Quota band three: no new calls until the window releases. */
{ code: "quota_exhausted"; release_at: Timestamp } | 
/**  No chat role configured: the app is in library form. */
{ code: "no_endpoint" } | { code: "endpoint"; detail: string } | { code: "keychain"; detail: string } | { code: "io"; detail: string };

export type AppForm = 
/**  No chat endpoint, or no network: roster and search only. */
"library" | 
/**  Host channel and the waiting panel. */
"full";

export type AppStatus = {
	form: AppForm,
	corpus: CorpusState,
	/**  No user name yet: show the first-run form. */
	needs_setup: boolean,
};

/**  Who can recall a fact. Shown on every row: the only place visibility surfaces. */
export type Audience = { kind: "world" } | { kind: "participants"; channel: ChannelId; persons: PersonRef[] } | 
/**  One person's own observation (`self` in the world model). */
{ kind: "own"; person: PersonRef };

export type Author = { kind: "user" } | 
/**  The in-world assistant. */
{ kind: "host" } | { kind: "person"; id: PersonId };

/**  The call shapes spending is broken down by. */
export type CallShape = "direct" | "group" | "opening" | "ask" | "host" | "wrapup";

/**  A person offered for something, with one line from the material that matched. */
export type Candidate = {
	person: PersonRef,
	mode: Mode,
	reason: string,
	citation: Citation | null,
};

/**  A pinned question and everything that hangs off it. */
export type CaseFile = {
	task: TaskSummary,
	/**  Each request made under it, with its reply once there is one. */
	trail: TrailEntry[],
	conclusion: FactView | null,
	/**  Messages elsewhere that responded to the conclusion. */
	reactions: MessageRef[],
};

export type ChannelId = string;

export type ChannelKind = "direct" | "group" | 
/**  The host's own channel. */
"host";

export type ChannelSummary = {
	id: ChannelId,
	kind: ChannelKind,
	origin: Origin,
	participants: PersonRef[],
	topic: string | null,
	mode: Mode,
	last_at: Timestamp | null,
};

/**
 *  Portable pointer into the corpus. Chunk ids are content hashes and change when a page
 *  changes, so the page and span travel with them for re-resolution.
 */
export type Citation = {
	page: string,
	revid: number,
	span_from: number,
	span_to: number,
	chunk_id: string,
};

export type CitationStatus = 
/**  The chunk id still exists. */
"current" | 
/**  The page changed; this is the best-overlapping passage of the new version. */
"updated" | 
/**  Nothing in the current corpus matches; only the stored links remain. */
"gone";

export type CitationView = {
	status: CitationStatus,
	passage: Passage | null,
	source_url: string | null,
	revision_url: string | null,
};

/**
 *  The header's clock. Derived from the local wall clock on every call, never stored.
 * 
 *  The in-world year is the local year minus an offset that belongs to the corpus, not to
 *  this code: it is read from the folio manifest key `clock.year_offset`, written by the
 *  pack. Month and day are the local ones.
 */
export type Clock = {
	in_world: InWorldDate,
	/**  Local time, `HH:MM`. */
	local_time: string,
};

/**  How much the corpus supports an answer, as retrieval measured it. */
export type Confidence = "high" | "medium" | "low";

export type CorpusState = { state: "missing" } | { state: "loaded"; name: string; 
/**  The local encoder differs from the corpus's: show a banner, keep going. */
encoder_mismatch: boolean } | 
/**  Refused: unknown format version. The user needs a newer app. */
{ state: "unsupported_version"; format_version: number } | 
/**  Refused: the corpus requires a reader feature this build lacks. */
{ state: "missing_requirement"; requirement: string };

/**  The waiting panel: pure data, no model call. */
export type Digest = {
	items: Waiting[],
};

export type EndpointsView = {
	profiles: ProfileView[],
	roles: Roles | null,
	/**  Starting points for "add". */
	presets: Profile[],
};

export type FactFilter = {
	scope: FactScope,
	/**  Only facts about, or recalled by, this person. */
	person: PersonId | null,
	task: TaskId | null,
};

export type FactId = string;

export type FactKind = "fact" | "commitment" | "conclusion" | "hurt";

export type FactList = {
	total: number,
	deleted: number,
	items: FactView[],
};

/**  The world drawer's filter chips. */
export type FactScope = "all" | "world" | "own" | "commitment" | "hurt" | "deleted";

export type FactView = {
	id: FactId,
	author: Author,
	audience: Audience,
	kind: FactKind,
	about: About | null,
	due: Timestamp | null,
	delivered: boolean,
	text: string,
	retracted: boolean,
	created_at: Timestamp,
};

/**  An image the user attaches; sent to the model as a multimodal part. */
export type ImagePart = {
	/**  `image/png`, `image/jpeg`, ... */
	mime: string,
	data_base64: string,
};

export type InWorldDate = {
	year: number,
	month: number,
	day: number,
};

/**  A file on this machine the UI may display or play (avatar, note, audio, attachment). */
export type MediaFile = {
	path: string,
};

export type Message = {
	id: MessageId,
	channel: ChannelId,
	author: Author,
	/**  As written, scene lines included; the UI splits on the scene marker. */
	text: string,
	/**  Visible action lines, in call order. */
	actions: ToolAction[],
	attachment: MediaFile | null,
	cites: Citation[],
	/**  Low: render the thin-archive marker. */
	confidence: Confidence | null,
	/**  A retelling of something said elsewhere. */
	relayed: boolean,
	/**  The request this message answers. */
	task: TaskId | null,
	note: MediaFile | null,
	at: Timestamp,
};

/**
 *  A message is complete and stored: a finished stream, a user message echoed back,
 *  an unprompted opening, an interjection.
 */
export type MessageAdded = {
	message: Message,
};

/**  A chunk of a reply being generated. `message` is stable across the stream. */
export type MessageDelta = {
	channel: ChannelId,
	message: MessageId,
	author: Author,
	delta: string,
};

export type MessageId = string;

export type MessageRef = {
	channel: ChannelId,
	message: MessageId,
	author: Author,
	excerpt: string,
};

/**  Whether a person or a group may act without being addressed. */
export type Mode = 
/**  May speak unprompted (with a seed, within the daily limits). */
"enabled" | 
/**  Never speaks first; still answers when triggered. Everyone starts here. */
"frozen" | 
/**  Cannot be triggered and never appears in any option offered to a model. */
"disabled";

/**  A person or group changed mode, by the user or by the host on the user's behalf. */
export type ModeChanged = {
	target: Target,
	mode: Mode,
};

/**
 *  What is known about one model on one profile. Unknown fields fall back to parameters
 *  (`cost.c`, `cost.o`) or to the conservative behaviour (no forced tool: wrap-up skipped).
 */
export type Model = {
	id: string,
	forced_tool?: boolean | null,
	context_window?: number | null,
	cache_min_prefix?: number | null,
	cache_breakpoints?: number | null,
	price_in?: number | null,
	price_in_cached?: number | null,
	price_out?: number | null,
};

export type MonthDay = {
	month: number,
	day: number,
};

/**
 *  Shown as a system notification when the window is closed. The text is the
 *  person's own line.
 */
export type Notification = {
	person: PersonId,
	channel: ChannelId,
	message: MessageId,
	text: string,
};

export type Origin = "user" | "system";

export type Passage = {
	citation: Citation,
	template: string,
	header: string,
	text: string,
	persons: PersonRef[],
	source_url: string | null,
};

/**  A roster id from the corpus; stable across corpus versions. */
export type PersonId = string;

export type PersonPage = {
	person: PersonRef,
	/**  One descriptive line from the corpus profile. */
	summary: string | null,
	trust: number,
	mode: Mode,
	last_seen: Timestamp | null,
	tasks_done: number,
	companions: PersonRef[],
	/**  Read-aloud voice; `None` = endpoint default. */
	voice: string | null,
	channel: ChannelId | null,
};

/**  A person as a list row needs them: id plus the corpus display name. */
export type PersonRef = {
	id: PersonId,
	name: string,
};

export type Profile = {
	name: string,
	/**  OpenAI-style root; `GET {base_url}/models` lists its models. */
	base_url: string,
	wire_api: WireApi,
	model?: Model[],
};

export type ProfileView = {
	profile: Profile,
	/**  A key is in the keychain. The key itself never crosses this seam. */
	has_key: boolean,
};

/**  Local wall-clock times, `HH:MM`; `from` after `to` spans midnight. */
export type QuietHours = {
	from: string,
	to: string,
};

export type QuotaBand = 
/**  Below the quiet threshold: everything as usual. */
"open" | 
/**  Unprompted speech and interjections are off; user-initiated calls proceed. */
"quiet" | 
/**  No new calls until `release_at`. */
"exhausted";

/**  Quota use, band or release time changed. */
export type QuotaChanged = {
	status: QuotaStatus,
};

export type QuotaStatus = {
	tier: Tier,
	band: QuotaBand,
	/**  Empty on the tier without windows. */
	windows: QuotaWindow[],
	/**  The window deciding the band, when not open. */
	binding: WindowSpan | null,
	spent: ShapeSpend[],
};

export type QuotaWindow = {
	span: WindowSpan,
	/**  Fraction of the window's limit used, 0 and up. */
	used: number | null,
	/**  When enough usage rolls out of the window to leave the current band. */
	release_at: Timestamp | null,
};

export type Role = {
	profile: string,
	model: string,
	/**
	 *  Passed as the endpoint's reasoning parameter; one value per session, never per call.
	 *  Absent: send none and let the endpoint default.
	 */
	reasoning?: string | null,
};

/**  The roles the endpoints drawer can set. The persona role is maintainer-only. */
export type RoleKind = "chat" | "tts";

export type Roles = {
	/**  Every runtime call: direct, group, ask, openings, interjections, wrap-up, host. */
	chat: Role,
	/**  Read-aloud (`/audio/speech`). Absent: no play button. */
	tts?: Role | null,
	/**  Maintainer-only offline persona generation. The app never reads it. */
	persona?: Role | null,
};

export type Roster = {
	total: number,
	enabled: number,
	/**  In display order; empty groups are omitted. */
	groups: RosterGroup[],
};

/**  Grouping by trust and contact, never a number on the row. */
export type RosterBand = "close" | "acquainted" | "never_talked" | "disabled";

/**  Roster grouping changed (trust or contact moved people between groups). */
export type RosterChanged = {
	persons: PersonId[],
};

export type RosterGroup = {
	band: RosterBand,
	rows: RosterRow[],
};

export type RosterRow = {
	person: PersonRef,
	mode: Mode,
	recent: Activity | null,
	/**  People they often appear with in the corpus. */
	companions: PersonRef[],
};

/**  A line wrapped in these is scene description, rendered apart from speech. */
export type SceneMarker = {
	open: string,
	close: string,
};

export type SearchResults = {
	hits: Passage[],
	confidence: Confidence,
	/**  The name the query was normalised to, so the UI can say what it searched for. */
	understood_as: string | null,
};

export type Settings = {
	user_name: string | null,
	birthday: MonthDay | null,
	/**  `None`: no quiet hours. The engine fills the register default on first run. */
	quiet_hours: QuietHours | null,
	notifications: boolean,
};

export type ShapeSpend = {
	shape: CallShape,
	/**  Quota points in the tighter window. */
	points: number | null,
};

export type Target = { kind: "person"; id: PersonId } | { kind: "channel"; id: ChannelId };

export type TaskId = string;

export type TaskStatus = "active" | "done";

export type TaskSummary = {
	id: TaskId,
	question: string,
	/**  A pinned question may have nobody on it yet. */
	assignee: PersonRef | null,
	parent: TaskId | null,
	status: TaskStatus,
	pinned: boolean,
	channel: ChannelId | null,
	created_at: Timestamp,
};

/**  The intensity slider: the only quota control. */
export type Tier = "low" | "middle" | "high" | "extra_high" | "max" | 
/**  No windows; only the daily experience limits apply. */
"ultra";

/**
 *  RFC 3339 with offset (`2026-01-02T03:04:05+08:00`). Strings rather than integers: the
 *  TypeScript side has no lossless 64-bit integer, and a date string needs no glue.
 */
export type Timestamp = string;

/**  One tool call as the UI shows it: typed, so each kind gets its own i18n line. */
export type ToolAction = { tool: "search"; query: string } | { tool: "get_chunk"; chunk_id: string } | { tool: "request_join"; person: PersonRef | null; topic: string | null } | { tool: "remember"; text: string } | { tool: "report" } | { tool: "wrapup" } | { tool: "digest" } | { tool: "find_people"; topic: string } | { tool: "ask"; person: PersonRef; question: string } | { tool: "create_group"; members: PersonRef[] } | { tool: "set_mode"; target: Target; mode: Mode } | { tool: "forget"; fact: FactId };

/**  A tool call, shown as a visible action line under the message it belongs to. */
export type ToolCalled = {
	channel: ChannelId,
	message: MessageId,
	author: Author,
	action: ToolAction,
};

export type TrailEntry = {
	task: TaskSummary,
	reply: Message | null,
};

export type Waiting = {
	person: PersonRef,
	/**  Where a click goes. */
	channel: ChannelId,
	activity: Activity,
};

export type WindowSpan = "five_hours" | "seven_days";

export type WireApi = 
/**  `POST {base_url}/chat/completions` */
"chat" | 
/**  `POST {base_url}/responses` */
"responses";

/**
 *  Runtime phrasing from the corpus manifest, keyed like the UI's i18n keys; a missing
 *  key falls back to the UI's neutral default.
 */
export type Wording = {
	entries: { [key in string]: string },
	scene_marker: SceneMarker,
};

export type WorldChange = { kind: "fact"; id: FactId } | { kind: "task"; id: TaskId } | { kind: "channel"; id: ChannelId } | { kind: "trust"; person: PersonId } | { kind: "digest" };

/**  Narrative state changed; the UI refetches what it shows of it. */
export type WorldChanged = {
	changes: WorldChange[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

