"""Framework defaults for every piece of human-facing text a generated file contains.

One mechanism for all of it: a pack supplies `Pack.text`, a flat mapping from these keys to
its own wording, and `Pack.say(key, **fields)` looks the key up there first and here second.
The key set is the contract. The values below are deliberately plain English, so an
unconfigured pack produces something legible and obviously unlocalised rather than text in
a language this repository has no business choosing.

Values are `str.format` templates. A pack may reorder or drop fields, but not invent them.
"""

from __future__ import annotations

from collections.abc import Mapping

TEXT: Mapping[str, str] = {
    # ---- record kinds (coverage report, CLI tables) ----
    "record.scene": "scenes",
    "record.line": "lines (speech / narration / caption)",
    "record.choice": "branch points",
    "record.dossier": "character dossiers",
    "record.voice": "recorded voice lines",
    "record.lore": "encyclopaedia sections",
    "record.letter": "letters",
    "record.term": "glossary terms",
    "record.char_ref": "descriptions of characters without a page",
    "record.alias": "alias entries",
    # ---- guards ----
    "guard.G1": "counts: seed drift and produced-vs-stored reconciliation",
    "guard.G2": "constructs: markup outside the declared rules",
    "guard.G3": "empty: an in-scope page produced no records",
    "guard.G4": "identity: page-to-person resolution invariants",
    "guard.G5": "corpus: chunking coverage, size and redundancy invariants",
    # ---- coverage report ----
    "coverage.title": "# Coverage · {pack}",
    "coverage.intro": (
        "Generated by `forge build` (`forge report coverage`). Lists, section by section of the "
        "source's own table of contents, what was taken, what was not, and why."),
    "coverage.policy": "",
    "coverage.archive": "- Archive: `{name}`",
    "coverage.synced": "- Last content sync: {at}",
    "coverage.versions": "- Parser version: {parser} · pack version: {pack}",
    "coverage.pages": "- Pages held: {n:,}",
    "coverage.dispositions": (
        "- Dispositions: {archived} archived · {partial} partial · {excluded} excluded"),
    "coverage.sources": "## 1. By source section",
    "coverage.sources_head": "Section|Disposition|Count|Reason",
    "coverage.records": "## 2. Records",
    "coverage.records_head": "Record|Meaning|Count|Chars",
    "coverage.total_chars": "**Usable text: {mchars:.2f} M chars.**",
    "coverage.identity": "## 3. Identity: a page is not a person",
    "coverage.identity_head": "Item|Count",
    "coverage.roster_pages": "Roster pages",
    "coverage.persons": "Persons",
    "coverage.form_kind": "Form · {kind}",
    "coverage.multi_form": "Persons with more than one form",
    "coverage.scenes": "## 4. Scenes by category",
    "coverage.scenes_head": "Category|Scenes|Lines",
    "coverage.uncategorised": "(none)",
    "coverage.voices": "## 5. Voice lines by trigger (top {n})",
    "coverage.voices_head": "Trigger|Count",
    "coverage.guards": "## 6. Guards",
    "coverage.guards_head": "Guard|High|Low",
    "coverage.guards_note": (
        "Any high-severity finding fails the release gate. Every low-severity count must be "
        "attributed: an unattributed one is a high-severity finding in waiting."),
    "coverage.recon": "## 7. Produced vs stored",
    "coverage.recon_intro": (
        "Produced and stored counts are recorded separately; their difference must be "
        "explained by exact duplicates, or guard G1 fires."),
    "coverage.recon_head": "Record|Produced|Stored|Duplicates collapsed",
    # ---- figures report ----
    "figures.title": "# Figures",
    "figures.intro": (
        "Generated by `forge build` (`forge report figures`). **Do not edit by hand.**\n\n"
        "Documents cite the keys in this table instead of quoting values."),
    "figures.fingerprint": "- Build fingerprint: `{fingerprint}`",
    "figures.columns": "Key|Value|Target|Meaning",
    # ---- attribution ----
    "attribution.editor_unknown": "(see page history)",
    "attribution.history": "history",
    "attribution.unset": "(unset)",
    "attribution.page_placeholder": "page",
    # ---- per-page inspection ----
    "inspect.header": "> Archived text. Source {chars:,} characters, revid {revid}.",
    "inspect.header_note": "> This is what every downstream stage sees.",
    "inspect.forms": "**Forms of one person**: {forms}",
    "inspect.form_item": "{page} ({kind})",
    "inspect.scene_meta": "**Category** {category} · **Group** {group} · **Source** `{source_ref}`",
    "inspect.scene_counts": "{lines:,} lines, {choices:,} branch points.",
    "inspect.body": "## Body",
    "inspect.choice": "{mark}{options}",
    "inspect.fields": "## Fields",
    "inspect.dossier_body": "## Dossier",
    "inspect.items": "## Related text",
    "inspect.memoir": "## {kind}",
    "inspect.voices": "## Voice lines ({n})",
    "inspect.voice_line": "**[{title}]** `{trigger}`{condition}",
    "inspect.voice_condition": ", {condition}",
    "inspect.lore": "## Encyclopaedia sections ({n})",
    "inspect.untitled": "(body)",
    "inspect.letters": "## Letters ({n})",
    "inspect.letter_meta": "*From {sender} · {date}*",
    "inspect.terms": "## Glossary terms ({n})",
    "inspect.term": "Term",
    "inspect.category": "Category",
    "inspect.char_refs": "## Character descriptions (showing {shown} of {total})",
    "inspect.char_ref_title": "### {name} *({group})*",
    "inspect.aliases": "## Aliases (showing {shown} of {total})",
    "inspect.aliases_note": (
        "> This page yields dictionary entries rather than corpus units."),
    "inspect.alias_head": "Alias|Target",
    "inspect.findings": "## Guard findings",
    "inspect.empty": "*(This page produced no records; see its guard findings.)*",
    # ---- sampling ----
    "samples.title": "# Samples",
    "samples.intro": (
        "Generated at the end of every `forge build` (and so every `forge sync`); "
        "`forge report samples` rebuilds it alone. Each page is written three ways: as "
        "fetched, as records, and as archived text. Nothing is random: every page of the last "
        "sync's changes, then fixed boundary cases per route. Do not edit."),
    "samples.status": "## Sync status",
    "samples.sync": "- {kind} at {at} · watermark {watermark} · pages held {pages:,}",
    "samples.sync.first": "First sync",
    "samples.sync.full": "Full sync",
    "samples.sync.incremental": "Incremental sync",
    "samples.sync.none": "No sync recorded",
    "samples.delta": "- This sync: {changed:,} changed · {added:,} added · {removed:,} removed",
    "samples.records_head": "Kind|What|Records|Change",
    "samples.guards_head": "Guard|Checks|High|Low",
    "samples.quality": "## Formatting quality",
    "samples.quality_clean": "No markup residue found in any record text.",
    "samples.quality_head": "Kind|Residue|Records|Examples",
    "samples.changes": "## This sync's changes",
    "samples.changes_none": "The last sync changed nothing.",
    "samples.boundaries": "## Boundary samples",
    "samples.route": "### {route}",
    "samples.head": "Page|Why|Files",
    "samples.files": "[source]({source}) · [records]({records}) · [archived]({archived})",
    "samples.why.changed": "changed",
    "samples.why.added": "added",
    "samples.why.removed": "removed (as it was before removal)",
    "samples.why.first": "first by title",
    "samples.why.largest": "largest source",
    "samples.why.smallest": "smallest non-empty source",
    "samples.why.most_records": "most records",
    "samples.why.findings": "first with guard findings",
    "samples.why.empty": "first that produced nothing: {reason}",
    "samples.why.kind": "first yielding `{kind}` records",
    "samples.why.alias": "alias-producing page",
    "samples.why.multi_form": "first person with several forms",
}


def table_head(columns: str) -> list[str]:
    """`"A|B|C"` → a markdown header row and its rule. Column names are pack text."""
    cells = [c.strip() for c in columns.split("|")]
    return ["| " + " | ".join(cells) + " |", "| " + " | ".join("---" for _ in cells) + " |"]
